### ISSUE TITLE
User group can be different from user

### ISSUE THREAD

**Issue by sylvainmetayer** [moviedo/ansible-role-nvm#12]
Hello,

First, thanks for your repository, which is very useful ! 

I have an issue when using it on my work laptop, where my user (`A`) does not have a `A` group but a `domain users` since I connect via an LDAP.  This cause the role to fail because it can't find the associated group.

Is it possible to add a `nvm_group` which if not indicated, will fallback on `nvm_user` value ?

**Comment by sylvainmetayer** [comment]
Same issue with the $HOME path which is `user@ldap.domain` on my computer, not `user`

**Comment by moviedo** [comment]
For the path issue you have, you could always override `nvm_working_path` and `nvm_dest`.
```
- hosts: all
  roles:
  - role: moviedo.nvm
      nvm_user: vagrant
      nvm_version: "v0.35.2"
      nvm_node_version: "12.14.1"
      nvm_working_path: "~"
      nvm_dest: "~/.nvm"
```
I do like the relative paths for thoses items mentioned above.
